/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AcademyRouteImport } from './routes/academy'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as DesignStudioRouteImport } from './routes/design-studio'
import { Route as MembershipRouteImport } from './routes/membership'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as SupportRouteImport } from './routes/support'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as AccountGarageRouteImport } from './routes/account.garage'
import { Route as AccountOrdersRouteImport } from './routes/account.orders'
import { Route as AccountResetPasswordRouteImport } from './routes/account_.reset-password'
import { Route as AdminAuditLogsRouteImport } from './routes/admin.audit-logs'
import { Route as AdminDiagnosticsRouteImport } from './routes/admin.diagnostics'
import { Route as AdminEventsRouteImport } from './routes/admin.events'
import { Route as AdminModerationRouteImport } from './routes/admin.moderation'
import { Route as AdminNewslettersRouteImport } from './routes/admin.newsletters'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminSecurityRouteImport } from './routes/admin.security'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as LegalLiabilityRouteImport } from './routes/legal.liability'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as LegalReturnsRouteImport } from './routes/legal.returns'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as ShopSlugRouteImport } from './routes/shop.$slug'
import { Route as AdminSettingsPayoutsRouteImport } from './routes/admin.settings.payouts'
import { Route as AdminSettingsShopifyRouteImport } from './routes/admin.settings.shopify'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyRoute = AcademyRouteImport.update({
  id: '/academy',
  path: '/academy',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignStudioRoute = DesignStudioRouteImport.update({
  id: '/design-studio',
  path: '/design-studio',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipRoute = MembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountGarageRoute = AccountGarageRouteImport.update({
  id: '/garage',
  path: '/garage',
  getParentRoute: () => AccountRoute,
} as any)
const AccountOrdersRoute = AccountOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AccountRoute,
} as any)
const AccountResetPasswordRoute = AccountResetPasswordRouteImport.update({
  id: '/account_/reset-password',
  path: '/account/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditLogsRoute = AdminAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDiagnosticsRoute = AdminDiagnosticsRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRoute,
} as any)
const AdminModerationRoute = AdminModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNewslettersRoute = AdminNewslettersRouteImport.update({
  id: '/newsletters',
  path: '/newsletters',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSecurityRoute = AdminSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const LegalLiabilityRoute = LegalLiabilityRouteImport.update({
  id: '/legal/liability',
  path: '/legal/liability',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalReturnsRoute = LegalReturnsRouteImport.update({
  id: '/legal/returns',
  path: '/legal/returns',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopSlugRoute = ShopSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ShopRoute,
} as any)
const AdminSettingsPayoutsRoute = AdminSettingsPayoutsRouteImport.update({
  id: '/settings/payouts',
  path: '/settings/payouts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsShopifyRoute = AdminSettingsShopifyRouteImport.update({
  id: '/settings/shopify',
  path: '/settings/shopify',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/academy': typeof AcademyRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/community': typeof CommunityRoute
  '/design-studio': typeof DesignStudioRoute
  '/membership': typeof MembershipRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/shop': typeof ShopRouteWithChildren
  '/studio': typeof StudioRoute
  '/support': typeof SupportRoute
  '/wishlist': typeof WishlistRoute
  '/account/garage': typeof AccountGarageRoute
  '/account/orders': typeof AccountOrdersRoute
  '/account/reset-password': typeof AccountResetPasswordRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/diagnostics': typeof AdminDiagnosticsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/newsletters': typeof AdminNewslettersRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/users': typeof AdminUsersRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/legal/liability': typeof LegalLiabilityRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/returns': typeof LegalReturnsRoute
  '/legal/terms': typeof LegalTermsRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/admin/settings/payouts': typeof AdminSettingsPayoutsRoute
  '/admin/settings/shopify': typeof AdminSettingsShopifyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/academy': typeof AcademyRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/community': typeof CommunityRoute
  '/design-studio': typeof DesignStudioRoute
  '/membership': typeof MembershipRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/shop': typeof ShopRouteWithChildren
  '/studio': typeof StudioRoute
  '/support': typeof SupportRoute
  '/wishlist': typeof WishlistRoute
  '/account/garage': typeof AccountGarageRoute
  '/account/orders': typeof AccountOrdersRoute
  '/account/reset-password': typeof AccountResetPasswordRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/diagnostics': typeof AdminDiagnosticsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/newsletters': typeof AdminNewslettersRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/users': typeof AdminUsersRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/legal/liability': typeof LegalLiabilityRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/returns': typeof LegalReturnsRoute
  '/legal/terms': typeof LegalTermsRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/admin/settings/payouts': typeof AdminSettingsPayoutsRoute
  '/admin/settings/shopify': typeof AdminSettingsShopifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/academy': typeof AcademyRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/community': typeof CommunityRoute
  '/design-studio': typeof DesignStudioRoute
  '/membership': typeof MembershipRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/shop': typeof ShopRouteWithChildren
  '/studio': typeof StudioRoute
  '/support': typeof SupportRoute
  '/wishlist': typeof WishlistRoute
  '/account/garage': typeof AccountGarageRoute
  '/account/orders': typeof AccountOrdersRoute
  '/account_/reset-password': typeof AccountResetPasswordRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/diagnostics': typeof AdminDiagnosticsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/newsletters': typeof AdminNewslettersRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/users': typeof AdminUsersRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/legal/liability': typeof LegalLiabilityRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/returns': typeof LegalReturnsRoute
  '/legal/terms': typeof LegalTermsRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/admin/settings/payouts': typeof AdminSettingsPayoutsRoute
  '/admin/settings/shopify': typeof AdminSettingsShopifyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/about'
    | '/academy'
    | '/account'
    | '/admin'
    | '/blog'
    | '/cart'
    | '/checkout'
    | '/community'
    | '/design-studio'
    | '/membership'
    | '/reset-password'
    | '/search'
    | '/shop'
    | '/studio'
    | '/support'
    | '/wishlist'
    | '/account/garage'
    | '/account/orders'
    | '/account/reset-password'
    | '/admin/audit-logs'
    | '/admin/diagnostics'
    | '/admin/events'
    | '/admin/moderation'
    | '/admin/newsletters'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/security'
    | '/admin/users'
    | '/blog/$slug'
    | '/legal/liability'
    | '/legal/privacy'
    | '/legal/returns'
    | '/legal/terms'
    | '/shop/$slug'
    | '/admin/settings/payouts'
    | '/admin/settings/shopify'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/about'
    | '/academy'
    | '/account'
    | '/admin'
    | '/blog'
    | '/cart'
    | '/checkout'
    | '/community'
    | '/design-studio'
    | '/membership'
    | '/reset-password'
    | '/search'
    | '/shop'
    | '/studio'
    | '/support'
    | '/wishlist'
    | '/account/garage'
    | '/account/orders'
    | '/account/reset-password'
    | '/admin/audit-logs'
    | '/admin/diagnostics'
    | '/admin/events'
    | '/admin/moderation'
    | '/admin/newsletters'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/security'
    | '/admin/users'
    | '/blog/$slug'
    | '/legal/liability'
    | '/legal/privacy'
    | '/legal/returns'
    | '/legal/terms'
    | '/shop/$slug'
    | '/admin/settings/payouts'
    | '/admin/settings/shopify'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/about'
    | '/academy'
    | '/account'
    | '/admin'
    | '/blog'
    | '/cart'
    | '/checkout'
    | '/community'
    | '/design-studio'
    | '/membership'
    | '/reset-password'
    | '/search'
    | '/shop'
    | '/studio'
    | '/support'
    | '/wishlist'
    | '/account/garage'
    | '/account/orders'
    | '/account_/reset-password'
    | '/admin/audit-logs'
    | '/admin/diagnostics'
    | '/admin/events'
    | '/admin/moderation'
    | '/admin/newsletters'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/security'
    | '/admin/users'
    | '/blog/$slug'
    | '/legal/liability'
    | '/legal/privacy'
    | '/legal/returns'
    | '/legal/terms'
    | '/shop/$slug'
    | '/admin/settings/payouts'
    | '/admin/settings/shopify'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AboutRoute: typeof AboutRoute
  AcademyRoute: typeof AcademyRoute
  AccountRoute: typeof AccountRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  BlogRoute: typeof BlogRouteWithChildren
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  CommunityRoute: typeof CommunityRoute
  DesignStudioRoute: typeof DesignStudioRoute
  MembershipRoute: typeof MembershipRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SearchRoute: typeof SearchRoute
  ShopRoute: typeof ShopRouteWithChildren
  StudioRoute: typeof StudioRoute
  SupportRoute: typeof SupportRoute
  WishlistRoute: typeof WishlistRoute
  AccountResetPasswordRoute: typeof AccountResetPasswordRoute
  LegalLiabilityRoute: typeof LegalLiabilityRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalReturnsRoute: typeof LegalReturnsRoute
  LegalTermsRoute: typeof LegalTermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy': {
      id: '/academy'
      path: '/academy'
      fullPath: '/academy'
      preLoaderRoute: typeof AcademyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-studio': {
      id: '/design-studio'
      path: '/design-studio'
      fullPath: '/design-studio'
      preLoaderRoute: typeof DesignStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership': {
      id: '/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof MembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/garage': {
      id: '/account/garage'
      path: '/garage'
      fullPath: '/account/garage'
      preLoaderRoute: typeof AccountGarageRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/orders': {
      id: '/account/orders'
      path: '/orders'
      fullPath: '/account/orders'
      preLoaderRoute: typeof AccountOrdersRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account_/reset-password': {
      id: '/account_/reset-password'
      path: '/account/reset-password'
      fullPath: '/account/reset-password'
      preLoaderRoute: typeof AccountResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit-logs': {
      id: '/admin/audit-logs'
      path: '/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AdminAuditLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/diagnostics': {
      id: '/admin/diagnostics'
      path: '/diagnostics'
      fullPath: '/admin/diagnostics'
      preLoaderRoute: typeof AdminDiagnosticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/moderation': {
      id: '/admin/moderation'
      path: '/moderation'
      fullPath: '/admin/moderation'
      preLoaderRoute: typeof AdminModerationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/newsletters': {
      id: '/admin/newsletters'
      path: '/newsletters'
      fullPath: '/admin/newsletters'
      preLoaderRoute: typeof AdminNewslettersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/security': {
      id: '/admin/security'
      path: '/security'
      fullPath: '/admin/security'
      preLoaderRoute: typeof AdminSecurityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/legal/liability': {
      id: '/legal/liability'
      path: '/legal/liability'
      fullPath: '/legal/liability'
      preLoaderRoute: typeof LegalLiabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/returns': {
      id: '/legal/returns'
      path: '/legal/returns'
      fullPath: '/legal/returns'
      preLoaderRoute: typeof LegalReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$slug': {
      id: '/shop/$slug'
      path: '/$slug'
      fullPath: '/shop/$slug'
      preLoaderRoute: typeof ShopSlugRouteImport
      parentRoute: typeof ShopRoute
    }
    '/admin/settings/payouts': {
      id: '/admin/settings/payouts'
      path: '/settings/payouts'
      fullPath: '/admin/settings/payouts'
      preLoaderRoute: typeof AdminSettingsPayoutsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings/shopify': {
      id: '/admin/settings/shopify'
      path: '/settings/shopify'
      fullPath: '/admin/settings/shopify'
      preLoaderRoute: typeof AdminSettingsShopifyRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AccountRouteChildren {
  AccountGarageRoute: typeof AccountGarageRoute
  AccountOrdersRoute: typeof AccountOrdersRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountGarageRoute: AccountGarageRoute,
  AccountOrdersRoute: AccountOrdersRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

interface AdminRouteChildren {
  AdminAuditLogsRoute: typeof AdminAuditLogsRoute
  AdminDiagnosticsRoute: typeof AdminDiagnosticsRoute
  AdminEventsRoute: typeof AdminEventsRoute
  AdminModerationRoute: typeof AdminModerationRoute
  AdminNewslettersRoute: typeof AdminNewslettersRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminSecurityRoute: typeof AdminSecurityRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminSettingsPayoutsRoute: typeof AdminSettingsPayoutsRoute
  AdminSettingsShopifyRoute: typeof AdminSettingsShopifyRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditLogsRoute: AdminAuditLogsRoute,
  AdminDiagnosticsRoute: AdminDiagnosticsRoute,
  AdminEventsRoute: AdminEventsRoute,
  AdminModerationRoute: AdminModerationRoute,
  AdminNewslettersRoute: AdminNewslettersRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminSecurityRoute: AdminSecurityRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminSettingsPayoutsRoute: AdminSettingsPayoutsRoute,
  AdminSettingsShopifyRoute: AdminSettingsShopifyRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface ShopRouteChildren {
  ShopSlugRoute: typeof ShopSlugRoute
}

const ShopRouteChildren: ShopRouteChildren = {
  ShopSlugRoute: ShopSlugRoute,
}

const ShopRouteWithChildren = ShopRoute._addFileChildren(ShopRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AboutRoute: AboutRoute,
  AcademyRoute: AcademyRoute,
  AccountRoute: AccountRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  BlogRoute: BlogRouteWithChildren,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  CommunityRoute: CommunityRoute,
  DesignStudioRoute: DesignStudioRoute,
  MembershipRoute: MembershipRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SearchRoute: SearchRoute,
  ShopRoute: ShopRouteWithChildren,
  StudioRoute: StudioRoute,
  SupportRoute: SupportRoute,
  WishlistRoute: WishlistRoute,
  AccountResetPasswordRoute: AccountResetPasswordRoute,
  LegalLiabilityRoute: LegalLiabilityRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalReturnsRoute: LegalReturnsRoute,
  LegalTermsRoute: LegalTermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
